# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeMarkup, semigroups, tasty, tastyHunit
, tastyQuickcheck, text
}:

cabal.mkDerivation (self: {
  pname = "titlecase";
  version = "0.1.0.0";
  sha256 = "09zq7z3icziad12ssn663l32k6c5z31azzlhg789q635ab3dckn0";
  buildDepends = [ blazeMarkup semigroups text ];
  testDepends = [ semigroups tasty tastyHunit tastyQuickcheck text ];
  meta = {
    homepage = "https://github.com/nkaretnikov/titlecase";
    description = "Convert English words to title case";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
